# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    session:
        enabled: false
        #handler_id: null
        #handler_id: 'session.handler.native_file'
        #save_path: '%kernel.project_dir%/var/sessions'

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
